### ISSUE TITLE
Auto coin spin?

### ISSUE THREAD

**Issue by solomad** [Fildah/chronogg_telebot#2]
"Bot will coin spin evey day, some time from 18:00-21:00 (time is random)"
No auto-spin
<img width="651" alt="006" src="https://user-images.githubusercontent.com/24777671/61502568-1cf20380-a9dd-11e9-99a4-1f574c61a4b3.PNG">

**Comment by solomad** [comment]
From log.log. Tries are not "...18:00-21:00 (time is random)"

2019-07-17 18:00:00,001 ERROR:An uncaught error was raised while executing job spin_job
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
TypeError: spin_job() takes 2 positional arguments but 3 were given

2019-07-18 18:00:00,001 ERROR:An uncaught error was raised while executing job spin_job
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
TypeError: spin_job() takes 2 positional arguments but 3 were given

**Comment by Fildah** [comment]
Hi, thanks for making issues so I can fix the bugs. I pushed new bot.py with fix, please update.
